-- AMAZON E-COMMERCE DATABASE
-- INVENTORY TABLE

CREATE TABLE INVENTORY (
    INVENTORY_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER NOT NULL,
    SELLER_ID NUMBER NOT NULL,
    STOCK_QUANTITY NUMBER NOT NULL,
    STOCK_STATUS VARCHAR2(20) NOT NULL
);

-- ESTABLISH RELATIONSHIP WITH SELLER

ALTER TABLE INVENTORY
ADD FOREIGN KEY (SELLER_ID)
REFERENCES SELLER(SELLER_ID);

-- INSERT INVENTORY DATA

INSERT INTO INVENTORY VALUES
(1, 1, 101, 50, 'Available');

INSERT INTO INVENTORY VALUES
(2, 2, 102, 30, 'Available');

INSERT INTO INVENTORY VALUES
(3, 3, 103, 0, 'Unavailable');

INSERT INTO INVENTORY VALUES
(4, 4, 104, 25, 'Available');

INSERT INTO INVENTORY VALUES
(5, 5, 105, 0, 'Unavailable');

COMMIT;

-- DISPLAY INVENTORY DATA

SELECT * FROM INVENTORY;
ALTER TABLE INVENTORY
ADD FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID);