-- ORDER_DETAILS TABLE

CREATE TABLE ORDER_DETAILS (
    ORDER_DETAIL_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    UNIT_PRICE NUMBER(10,2)
);

-- FOREIGN KEY

ALTER TABLE ORDER_DETAILS
ADD CONSTRAINT FK_ORDER
FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS(ORDER_ID);

-- INSERT ORDER DETAILS

INSERT INTO ORDER_DETAILS
(ORDER_DETAIL_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE)
VALUES (1, 1, 1, 2, 500.00);

INSERT INTO ORDER_DETAILS
(ORDER_DETAIL_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE)
VALUES (2, 1, 2, 1, 200.00);

INSERT INTO ORDER_DETAILS
(ORDER_DETAIL_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE)
VALUES (3, 2, 4, 1, 850.00);

INSERT INTO ORDER_DETAILS
(ORDER_DETAIL_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE)
VALUES (4, 3, 3, 2, 750.00);

INSERT INTO ORDER_DETAILS
(ORDER_DETAIL_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE)
VALUES (5, 4, 5, 1, 650.00);

COMMIT;

-- DISPLAY ORDER DETAILS

SELECT * FROM ORDER_DETAILS;