-- ORDERS TABLE

CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    ORDER_DATE DATE NOT NULL,
    TOTAL_AMOUNT NUMBER(10,2)
);

-- INSERT ORDER DATA

INSERT INTO ORDERS
(ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT)
VALUES (1, 1, TO_DATE('20-09-2026','DD-MM-YYYY'), 1200.00);

INSERT INTO ORDERS
(ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT)
VALUES (2, 2, TO_DATE('20-09-2026','DD-MM-YYYY'), 850.00);

INSERT INTO ORDERS
(ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT)
VALUES (3, 3, TO_DATE('21-09-2026','DD-MM-YYYY'), 1500.00);

INSERT INTO ORDERS
(ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT)
VALUES (4, 1, TO_DATE('21-09-2026','DD-MM-YYYY'), 650.00);

INSERT INTO ORDERS
(ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT)
VALUES (5, 2, TO_DATE('21-09-2026','DD-MM-YYYY'), 2200.00);

COMMIT;

-- DISPLAY ORDER DATA

SELECT * FROM ORDERS;