-- PAYMENT TABLE

CREATE TABLE PAYMENT (
    PAYMENT_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    PAYMENT_METHOD VARCHAR2(30) NOT NULL,
    PAYMENT_STATUS VARCHAR2(20) NOT NULL,
    AMOUNT NUMBER(10,2) NOT NULL
);


-- FOREIGN KEY

ALTER TABLE PAYMENT
ADD CONSTRAINT FK_PAYMENT_ORDER
FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS(ORDER_ID);


-- STORE PAYMENT DETAILS

INSERT INTO PAYMENT
(PAYMENT_ID, ORDER_ID, PAYMENT_DATE, PAYMENT_METHOD, PAYMENT_STATUS, AMOUNT)
VALUES
(1, 1, TO_DATE('20-09-2026','DD-MM-YYYY'), 'UPI', 'Successful', 1200.00);

INSERT INTO PAYMENT
(PAYMENT_ID, ORDER_ID, PAYMENT_DATE, PAYMENT_METHOD, PAYMENT_STATUS, AMOUNT)
VALUES
(2, 2, TO_DATE('20-09-2026','DD-MM-YYYY'), 'Credit Card', 'Successful', 850.00);

INSERT INTO PAYMENT
(PAYMENT_ID, ORDER_ID, PAYMENT_DATE, PAYMENT_METHOD, PAYMENT_STATUS, AMOUNT)
VALUES
(3, 3, TO_DATE('21-09-2026','DD-MM-YYYY'), 'Debit Card', 'Successful', 1500.00);

INSERT INTO PAYMENT
(PAYMENT_ID, ORDER_ID, PAYMENT_DATE, PAYMENT_METHOD, PAYMENT_STATUS, AMOUNT)
VALUES
(4, 4, TO_DATE('21-09-2026','DD-MM-YYYY'), 'Cash on Delivery', 'Failed', 650.00);

INSERT INTO PAYMENT
(PAYMENT_ID, ORDER_ID, PAYMENT_DATE, PAYMENT_METHOD, PAYMENT_STATUS, AMOUNT)
VALUES
(5, 5, TO_DATE('21-09-2026','DD-MM-YYYY'), 'UPI', 'Successful', 2200.00);

COMMIT;


-- DISPLAY PAYMENT DETAILS

SELECT * FROM PAYMENT;


-- SUCCESSFUL TRANSACTIONS

SELECT *
FROM PAYMENT
WHERE PAYMENT_STATUS = 'Successful';


-- FAILED TRANSACTIONS

SELECT *
FROM PAYMENT
WHERE PAYMENT_STATUS = 'Failed';


-- UPDATE PAYMENT STATUS

UPDATE PAYMENT
SET PAYMENT_STATUS = 'Successful'
WHERE PAYMENT_ID = 4;

COMMIT;


-- ANALYZE PAYMENT METHODS

SELECT
    PAYMENT_METHOD,
    COUNT(*) AS TOTAL_TRANSACTIONS
FROM PAYMENT
GROUP BY PAYMENT_METHOD
ORDER BY TOTAL_TRANSACTIONS DESC;


-- PAYMENT METHOD AND TOTAL AMOUNT

SELECT
    PAYMENT_METHOD,
    COUNT(*) AS TOTAL_TRANSACTIONS,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM PAYMENT
WHERE PAYMENT_STATUS = 'Successful'
GROUP BY PAYMENT_METHOD
ORDER BY TOTAL_AMOUNT DESC;


-- PAYMENT TRANSACTION REPORT

SELECT
    P.PAYMENT_ID,
    P.ORDER_ID,
    O.CUSTOMER_ID,
    P.PAYMENT_METHOD,
    P.PAYMENT_DATE,
    P.PAYMENT_STATUS,
    P.AMOUNT
FROM PAYMENT P
JOIN ORDERS O
ON P.ORDER_ID = O.ORDER_ID
ORDER BY P.PAYMENT_DATE;


-- PAYMENT STATUS REPORT

SELECT
    PAYMENT_STATUS,
    COUNT(*) AS TOTAL_TRANSACTIONS,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM PAYMENT
GROUP BY PAYMENT_STATUS;