-- REVIEW AND RATING MANAGEMENT

-- 1. CREATE TABLES

CREATE TABLE REVIEW (
    REVIEW_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER,
    CUSTOMER_ID NUMBER,
    ORDER_ID NUMBER,
    REVIEW_TEXT VARCHAR2(500),
    REVIEW_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE RATING (
    RATING_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER,
    CUSTOMER_ID NUMBER,
    RATING NUMBER(1) CHECK (RATING BETWEEN 1 AND 5),
    RATING_DATE DATE DEFAULT SYSDATE
);


-- 2. STORE CUSTOMER FEEDBACK AND RATINGS

INSERT INTO REVIEW
VALUES (1, 1, 1, 1, 'Good product', SYSDATE);

INSERT INTO RATING
VALUES (1, 1, 1, 5, SYSDATE);

COMMIT;


-- 3. RETRIEVE PRODUCT REVIEW DETAILS

SELECT *
FROM REVIEW;


-- 4. CALCULATE AVERAGE PRODUCT RATINGS

SELECT Product_ID, AVG(Rating) AS Average_Rating
FROM RATING
GROUP BY Product_ID;


-- 5. IDENTIFY HIGHLY RATED PRODUCTS

SELECT Product_ID, AVG(Rating) AS Average_Rating
FROM RATING
GROUP BY Product_ID
HAVING AVG(Rating) >= 4;